export const ROUTES = {
  home: '/',
  introduction: '/introduction',
  whatIsMusicTherapy: '/what-is-music-therapy',
  awardWinners: '/award-winners',
  coreGroup: '/core-group',
  eMagazine: '/e-magazine',
  conferences: '/conferences',
  events: '/events',
  awardAnnouncement2026: '/award-announcement-2026',
  distanceLearning: '/distance-learning',
  onlineProgramme: '/online-programme',
  activityReports: '/activity-reports',
  agmActivityReport: '/agm/activity-report',
  bookshelf: '/bookshelf',
  lifeMembers: '/life-members',
  collaboratingInstitutions: '/collaborating-institutions',
  accreditation: '/accreditation',
  contact: '/contact',
  login: '/login',
  register: '/register',
  membership: '/membership',
}
